### PR TITLE
Bind method QGVScene::writeGraph + CMake update.

### PR DESCRIPTION
**Pull request by jmirabel**

### CODE REVIEW

**Comment by jmirabel** [comment]
@nim65s can you test this on gepgitlab please ?

**Comment by nim65s** [comment]
I can't, everything is on fire right now…
- the main computers for the CI are broken (a RAID array is currently rebuilding)
- these are also the computers generating the CI images, so the CI images are outdated anyway
- binaries on robotpkg are also out of date, this should be fixed by https://git.openrobots.org/issues/230

But I will test it as soon as possible :)

**Comment by jmirabel** [comment]
No hurry.

Le mar. 3 déc. 2019 à 12:36, Guilhem Saurel <notifications@github.com> a
écrit :

**Comment by jmirabel** [comment]
Hi @nim65s,
are the servers up again ? If so, can you launch the CI ?

**Comment by nim65s** [comment]
Here it is: https://gepgitlab.laas.fr/gsaurel/gepetto-viewer/pipelines/7517

**Comment by jmirabel** [comment]
Marvelous. Thank

**Pull request merged**
