### PR TITLE
Add support of cloud points

### PR DESCRIPTION
**Pull request by jcarpent**

### CODE REVIEW

**Comment by jmirabel** [comment]
Is there something specific to point cloud which you don't find in the badly named `LeafNodeLine` ?

**Comment by jcarpent** [comment]
These are points, not line.

**Comment by jcarpent** [comment]
OK. Redundant.

**Comment by jmirabel** [comment]
In case someone bump into this:
```python
gui.addCurve(name, points, color)
gui.setCurveMode(name, "POINTS")
# eventually
gui.setFloatProperty(name, "PointSize", pointSize)
```

**Pull request closed without merging**
