### PR TITLE
USE_QT4 -> PROJECT_USE_QT4

### PR DESCRIPTION
**Pull request by jmirabel**
@nim65s can this be merged quickly ?

### CODE REVIEW

**Comment by jmirabel** [comment]
You will anyway need it for the release if you include the plugins in the binaries, as mentioned in #136

**Comment by nim65s** [comment]
Thanks !

**Comment by nim65s** [comment]
I was way too quick, sorry.

1. this is master (not a big issue)
2. what about https://github.com/Gepetto/gepetto-viewer/blob/master/plugins/pyqcustomplot/CMakeLists.txt#L19 ?

**Comment by jmirabel** [comment]
>     1. this is master (not a big issue)

This was intended as it patches the broken master branch.

**Pull request merged**
