### PR TITLE
OSX: need GLDEBUGPROC to be define before any other Qt import

### PR DESCRIPTION
**Pull request by ymontmarin**
It was undone with the "format" commit, but for OSX, we need to define  GLDEBUGPROC before any other Qt import. This is done `gepetto/gui/fwd.hh`, so the include of this file must be the first in every gui folder files that import it.

### CODE REVIEW

**Comment by ymontmarin** [comment]
OK, so pre-commit is exatly undoing the fix needed..
Either we can in some way use a flag to ignore pre-commit for this, or we have to redefine GLDEBUGPROC as it is done in `gepetto/gui/fwd.hh` in every file where it is needed.

**Comment by ymontmarin** [comment]
Here is the commit before pre-commit undo it:
https://github.com/Gepetto/gepetto-viewer/pull/201/commits/01e6dd9c77ea4df0a46beebcd3903fb1ba07b9df

This GLDEBUGPROC is needed for OSX build

**Comment by nim65s** [comment]
You can add a comment between 2 includes to ensure linters won't change order

**Comment by nim65s** [comment]
Thanks

**Pull request merged**
