### PR TITLE
Fix bug for OSX systems + remove warnings

### PR DESCRIPTION
**Pull request by jcarpent**

### CODE REVIEW

**Comment by jcarpent** [comment]
@jmirabel After the validation of this PR, I will proceed to a new releae of gepetto-viewer and gepetto-viewer-corba if you agree.

**Comment by nim65s** [comment]
@jcarpent I already have one in progress, I can update it with your PRs.

**Comment by jmirabel** [comment]
Thanks.

**Comment by jcarpent** [comment]
@nim65s Yes, it would be nice. When will it be ready? The sooner is better for me.

**Comment by jcarpent** [comment]
@jmirabel Thanks for the quick merge.

**Comment by nim65s** [comment]
@jcarpent before lunch :)

**Comment by nim65s** [comment]
Done.

**Pull request merged**
