### PR TITLE
Fix issue related to APPLE systems

### PR DESCRIPTION
**Pull request by jcarpent**

### CODE REVIEW

**Comment by jcarpent** [comment]
After merging, I will need to do a release. @jmirabel Is it fine for you?

**Comment by nim65s** [comment]
I already have one waiting to be pushed, can you wait until monday ?

**Comment by jcarpent** [comment]
Sure

**Comment by jmirabel** [comment]
This typedef is a magic Apple thing ! If you have any link that explains this typedef, could you add it as a comment ?

I am fine with releasing GV.

**Comment by jcarpent** [comment]
@jmirabel This is now done as a new commit

**Comment by jmirabel** [comment]
Thanks.

**Comment by nim65s** [comment]
@jcarpent : I finished my release, you can put another one if you need.

**Pull request merged**
