### PR TITLE
Improve UI experience.

### PR DESCRIPTION
**Pull request by jmirabel**

### CODE REVIEW

**Comment by nim65s** [comment]
Hi,

It looks like this broke the  CI (it was OK for the PR before):
https://gepgitlab.laas.fr/gepetto/gepetto-viewer/-/jobs/68044:
```
…/src/node-property.cpp:513:9: error: 'class QComboBox' has no member named 'setCurrentText'; did you mean 'setCurrentIndex'?
cb->setCurrentText(QString::fromStdString(value));
```

It looks like an issue between QComboBox [Qt4](https://doc.qt.io/archives/qt-4.8/qcombobox.html) / [Qt5](https://doc.qt.io/qt-5/qcombobox.html).

**Comment by jmirabel** [comment]
You are right. setCurrentText is not available in Qt4.

**Comment by florent-lamiraux** [comment]
I get this error message:
/home/florent/devel/pyrene/src/gepetto-viewer/src/node-property.cpp:340:11: error: ‘QOverload’ was not declared in this scope

**Comment by jmirabel** [comment]
> Compiling with QT4, I get this error message:
> /home/florent/devel/pyrene/src/gepetto-viewer/src/node-property.cpp:340:11: error: ‘QOverload’ was not declared in this scope

Right. introduced in Qt 5.7.

**Comment by florent-lamiraux** [comment]
Now, I have the same error message as @nim65s :
.../src/node-property.cpp:513:9: error: ‘class QComboBox’ has no member named ‘setCurrentText’; did you mean ‘setCurrentIndex’?

**Comment by florent-lamiraux** [comment]
Now it is qInfo that is not defined:
src/gepetto-viewer/src/gui/mainwindow.cc:570:11: error: ‘qInfo’ was not declared in this scope

**Comment by florent-lamiraux** [comment]
After adding
`#include <gepetto/viewer/config-osg.h>` in `include/gepetto/gui/pick-handler.hh`,
I get the following error:
`/src/gepetto-viewer/tests/properties.cpp:29:10: fatal error: QtConcurrent: No such file or directory`
This is the last test, so we are almost there.

**Comment by jmirabel** [comment]
Thanks for the feedback @florent-lamiraux 
I now use my gepgitlab fork to check that everything works fine. I will push here when everything is ready.

**Comment by jmirabel** [comment]
Everything should be ok now.

**Comment by florent-lamiraux** [comment]
I pushed some correction to git@github.com:florent-lamiraux/gepetto-viewer.git.
It now compiles, but the tests do not pass.

**Comment by florent-lamiraux** [comment]
The following line fails
https://github.com/Gepetto/gepetto-viewer/blob/ebd9d4f8141641031b78ed2483bcffb4f73f3988/tests/nodes.cpp#L81
but method `applyConfiguration` does not seem to set dirty_ to false.

**Comment by florent-lamiraux** [comment]
Forget my previous comment. I did not get your latest version.

**Pull request merged**
