### PR TITLE
Sync submodule CMake + fix

### PR DESCRIPTION
**Pull request by jcarpent**

### CODE REVIEW

**Comment by nim65s** [comment]
https://gepgitlab.laas.fr/gepetto/gepetto-viewer/pipelines/8621 LGTM :)

**Comment by jcarpent** [comment]
@nim65s What does it mean?

**Comment by nim65s** [comment]
Looks Good To Me. I'm just manually doing stuff I already automatized but not deployed yet…

**Comment by jmirabel** [comment]
Thanks.

**Pull request merged**
