### PR TITLE
Compatibility with PythonQt 3.2

### PR DESCRIPTION
**Pull request by nim65s**
Hi,

I did some tests to update OSG to 3.6.5, and include the DAE plugin directly into robotpkg-openscenegraph, and provide robotpkg-qt5-osgqt, as since OSG 3.6.0, the Qt plugin is not part of the main OSG repository anymore.

This is required for ubuntu 20.04, as it provides OSG 3.6, without the DAE plugin and without the Qt plugin, so maintaining packages for 16.04, 18.04 and 20.04 with the same source would really ease things on my side.

Everything seems to work on devel for this :)

While there, I tried with to use PythonQt 3.2 from https://sourceforge.net/projects/pythonqt/files/pythonqt/PythonQt-3.2/ which seems to be a more recent version from the CMakeified one we are using for now. It seems that it doesn't support Qt4 anymore.

The library changed its name: this is `libPythonQt-Qt5-Python3.8.so` & `libPythonQt_QtAll-Qt5-Python3.8.so` now (it also work for other python versions), so I had to adapt FindPythonQt.cmake.

Also, the `PythonQt_QtBindings.h` header and its `PythonQt_init_QtBindings();` method are gone. I don't find any relevant documentation, release note, nor upgrade guide about that. 

@jmirabel : do you have any inputs for this ?

My plan is to provide robotpkg-pyXY-pythonqt with this 3.2 version from upstream, but if this lead to any trouble (eg. about this method), I can try to provide robotpkg-pyXY-qtZ-pythonqt with an older upstream version.

### CODE REVIEW

**Comment by jmirabel** [comment]
> Everything seems to work on devel for this :)

Great !



> Also, the `PythonQt_QtBindings.h` header and its `PythonQt_init_QtBindings();` method are gone. I don't find any relevant documentation, release note, nor upgrade guide about that.

Function `PythonQt_init_QtBindings` does more or less the same as what is in the extension QtAll. I think using `PythonQt_QtAll::init()` from `PythonQt_QtAll.h` should be enough.

**Comment by jmirabel** [comment]
> While there, I tried with to use PythonQt 3.2 from https://sourceforge.net/projects/pythonqt/files/pythonqt/PythonQt-3.2/ which seems to be a more recent version from the CMakeified one we are using for now. It seems that it doesn't support Qt4 anymore.

On this page, they say:
> NOTE: PythonQt has been moved to https://github.com/MeVisLab/pythonqt

**Comment by nim65s** [comment]
Thanks for your answer.

I added that. But the header moved into an `extensions/` directory, and I had to link to the other library, so I added a bit of CMake.

Now, testing the DAE plugin is easy: just load eg. anymal. Checking the Qt plugin is also easy: gepetto-gui menu wouldn't work without.

To test PythonQt use, I was able to open a python shell and `import PythonQt` in it.  The `pythonwidget.py` seems to load and display the widget, but I can't create a window:
```
File "…/gepetto-viewer-corba/examples/pyplugin/pythonwidget.py", line 67, in createWindow
    self.plugin.main.createView(str(self.nodeName.text))
ValueError: Called createView(std::string name) -> OSGWidget with wrong arguments: ('nodeName',)
```

The `qcustomplot_example`s are also not working:
```
AttributeError: module 'PythonQt' has no attribute 'QCustomPlot'
```

@jmirabel : How do you want to proceed ? I suggest to start with a binary release of things as they are now, with the new OSG, and its new DAE & Qt plugins. This will not break anything, as this feature was not yet available in the binaries anyway.

Moreover, for those tests, I upgraded robotpkg-collada-dom, but this new version is not compatible with the old roboptkg-osg-dae, as @cmastalli & @jcarpent already found out. So I'd like to get something working again asap x)

Ref https://github.com/Gepetto/gepetto-viewer-corba/issues/143 btw

**Comment by nim65s** [comment]
@jmirabel could you try this branch on your setup, to check that it doesn't break anything on your side for now ?

**Comment by nim65s** [comment]
> > NOTE: PythonQt has been moved to https://github.com/MeVisLab/pythonqt

Yes, but on this new page, they don't provide any release tag, so I can't package that.

ref https://github.com/MeVisLab/pythonqt/issues/12

**Comment by jmirabel** [comment]
> @jmirabel could you try this branch on your setup, to check that it doesn't break anything on your side for now ?

What should I do to try ? Uninstall PythonQt from Gepetto and install it from the link you provided ? That's all ?

**Comment by nim65s** [comment]
I think you should keep your current working OSG / DAE / Qt / PythonQt environment, and test this gepetto-viewer branch.

**Comment by jmirabel** [comment]
Everything compiles fine. I got a `AttributeError: module 'PythonQt.QtGui' has no attribute 'QGroupBox'
` on one of my Python plugin and the PythonQt Python module is almost empty. I don't understand why yet as the PythonQt_QtAll::init seems to do the same thing as the QtBindings one.

**Comment by jmirabel** [comment]
Applying this to https://github.com/Gepetto/pythonqt, branch qt5 solves the problem
```
diff --git a/extensions/CMakeLists.txt b/extensions/CMakeLists.txt
index fde4698..0b30c6e 100644
--- a/extensions/CMakeLists.txt
+++ b/extensions/CMakeLists.txt
@@ -10,7 +10,7 @@ if(PythonQt_Extensions)
   foreach(qtlib ${qtlibs})
     set(qt_wrapped_lib ${qtlib_to_wraplib_${qtlib}})
     if(${PythonQt_Wrap_Qt${qt_wrapped_lib}})
-      add_definitions("-D${PythonQt_Wrap_Qt${qt_wrapped_lib}}")
+      add_definitions("-DPythonQt_Wrap_Qt${qt_wrapped_lib}")
     endif()
   endforeach()

```

**Pull request merged**
